# Generated by Django 3.0.5 on 2021-01-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('main_body_img', models.ImageField(upload_to='images')),
                ('title_body', models.CharField(max_length=256)),
                ('title_icon', models.ImageField(upload_to='icons')),
            ],
        ),
    ]
