# Generated by Django 2.2.3 on 2021-02-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Subject',
            new_name='subject',
        ),
    ]
