# Generated by Django 2.2.3 on 2021-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210225_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='trending_discription',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='header',
            name='trending_image',
            field=models.ImageField(blank=True, upload_to='trending'),
        ),
        migrations.AddField(
            model_name='header',
            name='trending_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
